- hosts: ctfserver
  gather_facts: False

  tasks:
  - name: install pip and python 2
    raw: test -e /usr/bin/pip2 || (apt -y update && apt install -y python-pip)
    become: true


- hosts: ctfserver
  roles:
    - vpn
    - lxd_production
    - firewall
    - infrastructure_lxd
  tasks:
  - name: set timezone to UTC
    timezone:
      name: UTC
    become: yes


- hosts: ad_containers
  gather_facts: False

  tasks:
  - name: install pip and python 2
    raw: test -e /usr/bin/pip2 || (apt -y update && apt install -y python-pip)
    become: true


#- hosts: jeop1
#  roles:
#    - status_build_2019


- hosts: ad_containers
  roles:
     - { role: geerlingguy.pip, become: yes }
#     - ad_service_2020_common
#     - ad_service_2020_albsig_bank
#     - ad_service_2020_pwstore_api
#     - ad_service_2020_pizza
