"""empty message

Revision ID: 120a094c4df1
Revises: 491cd9968491
Create Date: 2019-04-27 15:36:51.064647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '120a094c4df1'
down_revision = '491cd9968491'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
