"""empty message

Revision ID: 491cd9968491
Revises: ae644f0cc83e
Create Date: 2019-04-27 15:23:03.584488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '491cd9968491'
down_revision = 'ae644f0cc83e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
