"""empty message

Revision ID: 7c484374fdbf
Revises: 4118a14563c1
Create Date: 2019-04-27 21:56:05.526046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c484374fdbf'
down_revision = '4118a14563c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
