"""empty message

Revision ID: 9ff1b0b3a0e7
Revises: a5fee27ccbf5
Create Date: 2019-04-27 13:04:06.984248

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9ff1b0b3a0e7'
down_revision = 'a5fee27ccbf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flag', 'cookie',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=5000),
               existing_nullable=True)
    op.alter_column('flag', 'flag_id',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=5000),
               existing_nullable=True)
    op.alter_column('script', 'is_bundle',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('script', 'is_working',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('team', 'is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('team', 'is_admin',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('script', 'is_working',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('script', 'is_bundle',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.alter_column('flag', 'flag_id',
               existing_type=sa.String(length=5000),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=True)
    op.alter_column('flag', 'cookie',
               existing_type=sa.String(length=5000),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=True)
    # ### end Alembic commands ###
