"""empty message

Revision ID: a5fee27ccbf5
Revises: a4272eaee700
Create Date: 2019-04-27 12:56:05.005960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5fee27ccbf5'
down_revision = 'a4272eaee700'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
