"""empty message

Revision ID: c6e71b41d1d7
Revises: 120a094c4df1
Create Date: 2019-04-27 15:38:41.301277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6e71b41d1d7'
down_revision = '120a094c4df1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
