---

- include: lxd_base.yml
- include: zfs_storage.yml
- include: template_infrastructure.yml
- include: ad_infrastructure.yml
- include: jeopardy_infrastructure.yml
- include: gameserver_infrastructure.yml



# TODO https://github.com/lxc/lxd/blob/master/doc/production-setup.md